// <auto-generated />
using System;
using Billing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Billing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260819031310_ExternalReferencesAndPdfTemplates")]
    partial class ExternalReferencesAndPdfTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Billing.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ExternalSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_system");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_by");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Entities.DocumentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AffectationCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("affectation_code");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<decimal>("IgvAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("igv_amount");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TaxableAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("taxable_amount");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("unit_code");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("unit_price");

                    b.Property<decimal>("UnitValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("unit_value");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("document_items", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Entities.DocumentReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ReasonDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("reason_description");

                    b.Property<string>("RelatedDocumentTypeCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("related_document_type_code");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("series");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("document_references", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Entities.DocumentSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentTypeCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("document_type_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_number");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("series");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeCode", "Series")
                        .IsUnique();

                    b.ToTable("document_series", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Entities.DocumentSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorKind")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_kind");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("response_code");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Ticket")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ticket");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("document_submissions", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Entities.ElectronicDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AmountInWords")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("amount_in_words");

                    b.Property<string>("CarrierName")
                        .HasColumnType("text")
                        .HasColumnName("carrier_name");

                    b.Property<string>("CarrierRuc")
                        .HasColumnType("text")
                        .HasColumnName("carrier_ruc");

                    b.Property<decimal>("ChargeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("charge_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DestinationAddressLine")
                        .HasColumnType("text")
                        .HasColumnName("destination_address_line");

                    b.Property<string>("DestinationDepartment")
                        .HasColumnType("text")
                        .HasColumnName("destination_department");

                    b.Property<string>("DestinationDistrict")
                        .HasColumnType("text")
                        .HasColumnName("destination_district");

                    b.Property<string>("DestinationProvince")
                        .HasColumnType("text")
                        .HasColumnName("destination_province");

                    b.Property<string>("DestinationUbigeo")
                        .HasColumnType("text")
                        .HasColumnName("destination_ubigeo");

                    b.Property<string>("DigestValue")
                        .HasColumnType("text")
                        .HasColumnName("digest_value");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("DocumentTypeCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("document_type_code");

                    b.Property<string>("DriverDocumentNumber")
                        .HasColumnType("text")
                        .HasColumnName("driver_document_number");

                    b.Property<string>("DriverDocumentType")
                        .HasColumnType("text")
                        .HasColumnName("driver_document_type");

                    b.Property<string>("DriverLicense")
                        .HasColumnType("text")
                        .HasColumnName("driver_license");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal>("ExemptAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("exempt_amount");

                    b.Property<decimal>("ExportAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("export_amount");

                    b.Property<string>("ExternalEntity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_entity");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_reference");

                    b.Property<string>("ExternalSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_system");

                    b.Property<decimal>("FreeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("free_amount");

                    b.Property<decimal?>("GrossWeightKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("gross_weight_kg");

                    b.Property<decimal>("IgvAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("igv_amount");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<TimeOnly>("IssueTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("issue_time");

                    b.Property<string>("IssuerAddressLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer_address_line");

                    b.Property<string>("IssuerCountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer_country_code");

                    b.Property<string>("IssuerDepartment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer_department");

                    b.Property<string>("IssuerDistrict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer_district");

                    b.Property<string>("IssuerEmail")
                        .HasColumnType("text")
                        .HasColumnName("issuer_email");

                    b.Property<string>("IssuerEstablishmentCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer_establishment_code");

                    b.Property<string>("IssuerLegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer_legal_name");

                    b.Property<string>("IssuerPhone")
                        .HasColumnType("text")
                        .HasColumnName("issuer_phone");

                    b.Property<string>("IssuerProvince")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer_province");

                    b.Property<string>("IssuerRuc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("issuer_ruc");

                    b.Property<string>("IssuerTradeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer_trade_name");

                    b.Property<string>("IssuerUbigeo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer_ubigeo");

                    b.Property<string>("IssuerUrbanization")
                        .HasColumnType("text")
                        .HasColumnName("issuer_urbanization");

                    b.Property<decimal>("LineExtensionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_extension_amount");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<string>("OperationTypeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_type_code");

                    b.Property<string>("OriginAddressLine")
                        .HasColumnType("text")
                        .HasColumnName("origin_address_line");

                    b.Property<string>("OriginDepartment")
                        .HasColumnType("text")
                        .HasColumnName("origin_department");

                    b.Property<string>("OriginDistrict")
                        .HasColumnType("text")
                        .HasColumnName("origin_district");

                    b.Property<string>("OriginProvince")
                        .HasColumnType("text")
                        .HasColumnName("origin_province");

                    b.Property<string>("OriginUbigeo")
                        .HasColumnType("text")
                        .HasColumnName("origin_ubigeo");

                    b.Property<int?>("PackageCount")
                        .HasColumnType("integer")
                        .HasColumnName("package_count");

                    b.Property<decimal>("PayableAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("payable_amount");

                    b.Property<int>("PaymentForm")
                        .HasColumnType("integer")
                        .HasColumnName("payment_form");

                    b.Property<string>("RecipientAddressLine")
                        .HasColumnType("text")
                        .HasColumnName("recipient_address_line");

                    b.Property<string>("RecipientEmail")
                        .HasColumnType("text")
                        .HasColumnName("recipient_email");

                    b.Property<string>("RecipientIdentityNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recipient_identity_number");

                    b.Property<string>("RecipientIdentityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_identity_type");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("text")
                        .HasColumnName("requested_by");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("series");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SunatStatus")
                        .HasColumnType("integer")
                        .HasColumnName("sunat_status");

                    b.Property<decimal>("TaxInclusiveAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_inclusive_amount");

                    b.Property<decimal>("TaxableAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("taxable_amount");

                    b.Property<string>("TransferReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("transfer_reason_code");

                    b.Property<DateOnly?>("TransferStartDate")
                        .HasColumnType("date")
                        .HasColumnName("transfer_start_date");

                    b.Property<string>("TransportModeCode")
                        .HasColumnType("text")
                        .HasColumnName("transport_mode_code");

                    b.Property<decimal>("UnaffectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unaffected_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehiclePlate")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_plate");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSystem", "ExternalReference");

                    b.HasIndex("DocumentTypeCode", "Series", "Number")
                        .IsUnique();

                    b.HasIndex("ExternalSystem", "ExternalEntity", "ExternalId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Entities.GeneratedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("generated_files", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_payload");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Entities.Issuer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("EstablishmentCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("establishment_code");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("ruc");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.ToTable("issuers", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Entities.PdfTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("CommercialText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("commercial_text");

                    b.Property<string>("FooterText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("footer_text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("LogoStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_storage_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("primary_color");

                    b.Property<string>("TradeName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("pdf_templates", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Entities.DocumentItem", b =>
                {
                    b.HasOne("Billing.Domain.Entities.ElectronicDocument", null)
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Billing.Domain.Entities.DocumentReference", b =>
                {
                    b.HasOne("Billing.Domain.Entities.ElectronicDocument", null)
                        .WithMany("References")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Billing.Domain.Entities.DocumentSubmission", b =>
                {
                    b.HasOne("Billing.Domain.Entities.ElectronicDocument", null)
                        .WithMany("Submissions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Billing.Domain.Entities.GeneratedFile", b =>
                {
                    b.HasOne("Billing.Domain.Entities.ElectronicDocument", null)
                        .WithMany("Files")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Billing.Domain.Entities.Issuer", b =>
                {
                    b.OwnsOne("Billing.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("IssuerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("Department")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("department");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("district");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("address_line");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("province");

                            b1.Property<string>("Ubigeo")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("ubigeo");

                            b1.Property<string>("Urbanization")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("urbanization");

                            b1.HasKey("IssuerId");

                            b1.ToTable("issuers");

                            b1.WithOwner()
                                .HasForeignKey("IssuerId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Billing.Domain.Entities.ElectronicDocument", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Items");

                    b.Navigation("References");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
